# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Autolayout' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Autolayout
  # pod 'libextobjc/EXTScope', :git => 'https://github.com/jspahrsummers/libextobjc.git', :tag => '0.5'
  pod 'Masonry'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

  target 'AutolayoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutolayoutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
